/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/navigation`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/calendar` | `/calendar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings-screens/DateAndTimeSettings` | `/settings-screens/DateAndTimeSettings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings-screens/HelpAndFeedback` | `/settings-screens/HelpAndFeedback`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings-screens/PricingSettings` | `/settings-screens/PricingSettings`; params?: Router.UnknownInputParams; } | { pathname: `/contexts/TaskContext`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/navigation`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/calendar` | `/calendar`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings-screens/DateAndTimeSettings` | `/settings-screens/DateAndTimeSettings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings-screens/HelpAndFeedback` | `/settings-screens/HelpAndFeedback`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings-screens/PricingSettings` | `/settings-screens/PricingSettings`; params?: Router.UnknownOutputParams; } | { pathname: `/contexts/TaskContext`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/navigation${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/calendar${`?${string}` | `#${string}` | ''}` | `/calendar${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings-screens/DateAndTimeSettings${`?${string}` | `#${string}` | ''}` | `/settings-screens/DateAndTimeSettings${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings-screens/HelpAndFeedback${`?${string}` | `#${string}` | ''}` | `/settings-screens/HelpAndFeedback${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings-screens/PricingSettings${`?${string}` | `#${string}` | ''}` | `/settings-screens/PricingSettings${`?${string}` | `#${string}` | ''}` | `/contexts/TaskContext${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/navigation`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/calendar` | `/calendar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings-screens/DateAndTimeSettings` | `/settings-screens/DateAndTimeSettings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings-screens/HelpAndFeedback` | `/settings-screens/HelpAndFeedback`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings-screens/PricingSettings` | `/settings-screens/PricingSettings`; params?: Router.UnknownInputParams; } | { pathname: `/contexts/TaskContext`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
