/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `${'/(tabs)'}/settingsscreen` | `/settingsscreen`; params?: Router.UnknownInputParams; } | { pathname: `/../components/DateAndTime`; params?: Router.UnknownInputParams; } | { pathname: `/../components/General`; params?: Router.UnknownInputParams; } | { pathname: `/../components/HelpAndFeedback`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Pricing`; params?: Router.UnknownInputParams; } | { pathname: `/context/SettingContext`; params?: Router.UnknownInputParams; } | { pathname: `/../components/About`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Notifications`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Followus`; params?: Router.UnknownInputParams; } | { pathname: `/../components/terms`; params?: Router.UnknownInputParams; } | { pathname: `/../components/privacy-policy`; params?: Router.UnknownInputParams; } | { pathname: `/../components/auth`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/calendar` | `/calendar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `${'/(tabs)'}/settingsscreen` | `/settingsscreen`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/DateAndTime`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/General`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/HelpAndFeedback`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/Pricing`; params?: Router.UnknownOutputParams; } | { pathname: `/context/SettingContext`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/About`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/Notifications`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/Followus`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/terms`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/privacy-policy`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/auth`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/calendar` | `/calendar`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `${'/(tabs)'}/settingsscreen${`?${string}` | `#${string}` | ''}` | `/settingsscreen${`?${string}` | `#${string}` | ''}` | `/../components/DateAndTime${`?${string}` | `#${string}` | ''}` | `/../components/General${`?${string}` | `#${string}` | ''}` | `/../components/HelpAndFeedback${`?${string}` | `#${string}` | ''}` | `/../components/Pricing${`?${string}` | `#${string}` | ''}` | `/context/SettingContext${`?${string}` | `#${string}` | ''}` | `/../components/About${`?${string}` | `#${string}` | ''}` | `/../components/Notifications${`?${string}` | `#${string}` | ''}` | `/../components/Followus${`?${string}` | `#${string}` | ''}` | `/../components/terms${`?${string}` | `#${string}` | ''}` | `/../components/privacy-policy${`?${string}` | `#${string}` | ''}` | `/../components/auth${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/calendar${`?${string}` | `#${string}` | ''}` | `/calendar${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `${'/(tabs)'}/settingsscreen` | `/settingsscreen`; params?: Router.UnknownInputParams; } | { pathname: `/../components/DateAndTime`; params?: Router.UnknownInputParams; } | { pathname: `/../components/General`; params?: Router.UnknownInputParams; } | { pathname: `/../components/HelpAndFeedback`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Pricing`; params?: Router.UnknownInputParams; } | { pathname: `/context/SettingContext`; params?: Router.UnknownInputParams; } | { pathname: `/../components/About`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Notifications`; params?: Router.UnknownInputParams; } | { pathname: `/../components/Followus`; params?: Router.UnknownInputParams; } | { pathname: `/../components/terms`; params?: Router.UnknownInputParams; } | { pathname: `/../components/privacy-policy`; params?: Router.UnknownInputParams; } | { pathname: `/../components/auth`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/calendar` | `/calendar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
